#!/usr/bin/python
import sqlite3


def connect_to_db():
    """Open the SQLite file, creating database.db if it does not exist yet."""
    conn = sqlite3.connect("database.db")
    return conn


def create_db_table():
    conn = None
    try:
        conn = connect_to_db()
        conn.execute(
            """
            CREATE TABLE users (
                user_id INTEGER PRIMARY KEY NOT NULL,
                name TEXT NOT NULL,
                email TEXT NOT NULL,
                phone TEXT NOT NULL,
                address TEXT NOT NULL,
                country TEXT NOT NULL
            );
            """
        )
        conn.commit()
        print("User table created successfully")
    except sqlite3.Error as error:
        # Happens on later runs because the table already exists.
        print(f"User table creation failed - Maybe table already exists ({error})")
    finally:
        if conn:
            conn.close()


def insert_user(user):
    inserted_user = {}
    conn = None
    try:
        conn = connect_to_db()
        cur = conn.cursor()
        cur.execute(
            "INSERT INTO users (name, email, phone, address, country) VALUES (?, ?, ?, ?, ?)",
            (
                user["name"],
                user["email"],
                user["phone"],
                user["address"],
                user["country"],
            ),
        )
        conn.commit()
        # user_id is generated by SQLite; lastrowid is that new id.
        inserted_user = get_user_by_id(cur.lastrowid)
    except sqlite3.Error:
        if conn:
            conn.rollback()
    finally:
        if conn:
            conn.close()
    return inserted_user


def row_to_user(row):
    return {
        "user_id": row["user_id"],
        "name": row["name"],
        "email": row["email"],
        "phone": row["phone"],
        "address": row["address"],
        "country": row["country"],
    }


def get_users():
    users = []
    conn = None
    try:
        conn = connect_to_db()
        # Row lets us read columns by name instead of by position.
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute("SELECT * FROM users")
        rows = cur.fetchall()
        for row in rows:
            users.append(row_to_user(row))
    except sqlite3.Error:
        users = []
    finally:
        if conn:
            conn.close()
    return users


def get_user_by_id(user_id):
    user = {}
    conn = None
    try:
        conn = connect_to_db()
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute("SELECT * FROM users WHERE user_id = ?", (user_id,))
        row = cur.fetchone()
        if row is None:
            return {}
        user = row_to_user(row)
    except sqlite3.Error:
        user = {}
    finally:
        if conn:
            conn.close()
    return user


def update_user(user):
    updated_user = {}
    conn = None
    try:
        conn = connect_to_db()
        cur = conn.cursor()
        cur.execute(
            """
            UPDATE users
            SET name = ?, email = ?, phone = ?, address = ?, country = ?
            WHERE user_id = ?
            """,
            (
                user["name"],
                user["email"],
                user["phone"],
                user["address"],
                user["country"],
                user["user_id"],
            ),
        )
        conn.commit()
        updated_user = get_user_by_id(user["user_id"])
    except sqlite3.Error:
        if conn:
            conn.rollback()
        updated_user = {}
    finally:
        if conn:
            conn.close()
    return updated_user


def delete_user(user_id):
    message = {}
    conn = None
    try:
        conn = connect_to_db()
        conn.execute("DELETE FROM users WHERE user_id = ?", (user_id,))
        conn.commit()
        message["status"] = "User deleted successfully"
    except sqlite3.Error:
        if conn:
            conn.rollback()
        message["status"] = "Cannot delete user"
    finally:
        if conn:
            conn.close()
    return message


if __name__ == "__main__":
    create_db_table()
